# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    paths: ["src/**", "test/**", "package.json", "tsconfig.json", "bun.lockb", ".github/workflows/npm-publish.yml"]
    branches:
      - main
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun test
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.npm_token }}
      # - run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.npm_token}}
