name: Publish rust

on:
  push:
    paths: ['selenite-commons-rs/**', '.github/workflows/rust-package.yml']
    branches:
      - main
  release:
    types: [created]

jobs:
  publish-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ''
      - uses: oven-sh/setup-bun@v2
      - run: bun i -g wasm-pack
      - run: bun run wasm
      - uses: JS-DevTools/npm-publish@v3
        with:
          package: selenite-commons-rs/pkg
          token: ${{ secrets.npm_token }}
