name: Publish rust

on:
  push:
    paths:
      [
        'src-tauri/**',
        '.github/workflows/rust-package.yml'
      ]
    branches:
      - main
  release:
    types: [created]

jobs:
  publish-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: oven-sh/setup-bun@v2
      - run: bun i -g wasm-pack
      - run: bun run wasm
      - run: bun run wasmPublish